name: safesignal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ⭐ Required dependencies
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.5.0
  flutter_secure_storage: ^9.0.0

  # ⭐ SQLite + path utilities
  sqflite: ^2.3.0
  path: ^1.9.0

  flutter_blue_plus: ^1.0.0

  # Mesh Analytics
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/db/safesignal.db



